LLM_PROXY_SERVER: ''
  # LLM API的代理服务器地址（如果需要）(但是暂未实现该功能)
LLM_MODEL: gemini-1.5-pro-exp-0827
  # 使用的LLM模型名称
FAST_LLM_MODEL: gemini-1.5-flash-exp-0827
  # 用于快速回复的 LLM 模型
LLM_MAX_TOKENS: 4096
  # LLM生成的最大token数
LLM_TEMPERATURE: 0.7
  # LLM生成的温度参数，控制输出的随机性（0.0-2.0）
RESPONSE_TIMEOUT: 30
  # API调用超时时间（秒）
TRIGGER_PROBABILITY: 0.5
  # AI主动发言的概率（0.0-1.0）
TRIGGER_MESSAGE_INTERVAL: 5
  # 触发AI主动发言的消息间隔数
CONTEXT_MESSAGE_COUNT: 30
  # 保留的上下文消息数量
SUPERUSERS: []
  # 超级用户的QQ号列表
ENABLED_GROUPS: []
  # 启用插件的群号列表
CHARACTER_CARDS_DIR: res/character
  # 角色卡片目录路径
PRESET_DIR: res/preset
  # 预设文件目录路径
WORLD_INFO_DIR: res/world
  # 世界信息文件目录路径
IMAGE_SAVE_PATH: data/images
  # 图片保存路径
DEFAULT_WORLDBOOK: 世界书条目示例
  # 默认世界书名称
DEFAULT_PRESET: 预设示例
  # 默认预设名称
DEFAULT_CHARACTER_ID: nolll
  # 默认角色ID
ENABLE_SCHEDULER: true
  # 是否启用定时任务
INACTIVE_THRESHOLD: 3600
  # 群聊不活跃阈值（秒）
MORNING_GREETING_TIME: 08:30
  # 早安问候时间
DATABASE_URL: sqlite:///friend_bot.db
  # 数据库连接URL
LOG_LEVEL: INFO
  # 日志级别
CHAT_HISTORY_LIMIT: 3000
  # 聊天历史记录最大保存条数
MAX_RETRIES: 3
  # API调用最大重试次数
RETRY_INTERVAL: 1.0
  # API调用重试间隔（秒）
CACHE_EXPIRY_TIME: 1800
  # 缓存过期时间（秒）(未实装)
CHAT_COOLDOWN: 10
  # 两次回复之间的冷却时间（秒）(未实装)
MAX_DAILY_INTERACTIONS: 100
  # 每日最大交互次数限制(未实装)
VERSION: 1.0.0
  # 插件版本号
DEBUG_MODE: false
  # 是否启用调试模式
RES_PATH: res
  # 资源文件根目录路径
LOG_TO_FILE: false
  # 是否将日志输出到文件
LOG_DIR: 
  C:\0111\0111\Tools\nonebot2\mmttyy\mmttyy\plugins\nonebot_plugin_real_netizens\logs
  # 日志文件存储目录
LOG_FILE_NAME: nonebot_plugin_real_netizens.log
  # 日志文件名
LOG_FILE_MAX_SIZE: 10
  # 单个日志文件的最大大小（MB）
LOG_FILE_BACKUP_COUNT: 5
  # 保留的日志文件备份数量
