# config/friend_config.yml
#这两个配置需要在.env中添加
#LLM_API_BASE=https://api.example.com
#LLM_API_KEY=your-api-key
# 快速模型配置
FAST_LLM_MODEL: gemini-1.5-flash-exp-0827
# 高质量模型配置
LLM_MODEL: gemini-1.5-pro-exp-0827
# LLM生成的最大token数
LLM_MAX_TOKENS: 2096
# LLM生成的温度参数，控制输出的随机性（0.0-1.0）
LLM_TEMPERATURE: 0.9
# AI主动发言的概率（0.0-1.0）
TRIGGER_PROBABILITY: 0.6
# 触发AI主动发言的消息间隔数
TRIGGER_MESSAGE_INTERVAL: 3
# 群聊消息上下文条数上限
CONTEXT_MESSAGE_COUNT: 50
# API 代理配置（暂时没用上）
# LLM_PROXY_SERVER: ""
# RESPONSE_TIMEOUT: 30
# 用户和群组配置
SUPERUSERS: []
ENABLED_GROUPS: []
# 资源目录配置
CHARACTER_CARDS_DIR: "res/character"
PRESET_DIR: "res/preset"
WORLD_INFO_DIR: "res/world"
# 其他配置项
DEFAULT_CHARACTER_ID: "default"
INACTIVE_THRESHOLD: 3600
MORNING_GREETING_TIME: "08:00"
DATABASE_URL: "sqlite:///friend_bot.db"
LOG_LEVEL: "INFO"
CHAT_HISTORY_LIMIT: 1000
# 新增配置项
MAX_RETRIES: 3
RETRY_INTERVAL: 1.0
IMPRESSION_UPDATE_INTERVAL: 3600
MAX_IMPRESSION_LENGTH: 500
CHAT_COOLDOWN: 10
MAX_DAILY_INTERACTIONS: 100
VERSION: "1.0.0"
DEBUG_MODE: false
