CACHE_EXPIRY_TIME: 1800
CHARACTER_CARDS_DIR: res/character
CHAT_COOLDOWN: 10
CHAT_HISTORY_LIMIT: 3000
CONTEXT_MESSAGE_COUNT: 30
DATABASE_URL: sqlite:///friend_bot.db
DEBUG_MODE: false
DEFAULT_CHARACTER_ID: nolll
DEFAULT_PRESET: "\u9884\u8BBE\u793A\u4F8B"
DEFAULT_WORLDBOOK: "\u4E16\u754C\u4E66\u6761\u76EE\u793A\u4F8B"
ENABLED_GROUPS: []
ENABLE_SCHEDULER: true
IMAGE_SAVE_PATH: data/images
INACTIVE_THRESHOLD: 3600
LLM_MAX_TOKENS: 4096
LLM_MODEL: gemini-1.5-pro-exp-0827
LLM_PROXY_SERVER: ''
LLM_TEMPERATURE: 0.7
LOG_DIR: !!python/object/apply:pathlib.WindowsPath
- C:\
- '0111'
- '0111'
- Tools
- nonebot2
- mmttyy
- mmttyy
- plugins
- nonebot_plugin_real_netizens
- logs
LOG_FILE_BACKUP_COUNT: 5
LOG_FILE_MAX_SIZE: 10
LOG_FILE_NAME: nonebot_plugin_real_netizens.log
LOG_LEVEL: INFO
LOG_TO_FILE: false
MAX_DAILY_INTERACTIONS: 100
MAX_RETRIES: 3
MORNING_GREETING_TIME: 08:30
PRESET_DIR: res/preset
RESPONSE_TIMEOUT: 30
RES_PATH: res
RETRY_INTERVAL: 1.0
SUPERUSERS: []
TRIGGER_MESSAGE_INTERVAL: 5
TRIGGER_PROBABILITY: 0.5
VERSION: 1.0.0
WORLD_INFO_DIR: res/world
