# config/friend_config.yml
#这两个配置需要在.env中添加
#LLM_API_BASE=https://api.example.com
#LLM_API_KEY=your-api-key

LLM_MODEL: gemini-1.5-flash-exp-0827
LLM_MAX_TOKENS: 1096
LLM_TEMPERATURE: 0.9
TRIGGER_PROBABILITY: 0.6
TRIGGER_MESSAGE_INTERVAL: 3
CONTEXT_MESSAGE_COUNT: 50  # 群聊消息上下文条数上限
