# config/friend_config.yml
#这两个配置需要在.env中添加
#LLM_API_BASE=https://api.example.com
#LLM_API_KEY=your-api-key

#使用的LLM模型名称
LLM_MODEL: gemini-1.5-flash-exp-0827
# LLM生成的最大token数
LLM_MAX_TOKENS: 1096
# LLM生成的温度参数，控制输出的随机性（0.0-1.0）
LLM_TEMPERATURE: 0.9
# AI主动发言的概率（0.0-1.0）
TRIGGER_PROBABILITY: 0.6
# 触发AI回复的消息间隔数
TRIGGER_MESSAGE_INTERVAL: 3
# 群聊消息上下文条数上限
CONTEXT_MESSAGE_COUNT: 50
